import { Insight } from './insight';

import * as moment from 'moment';

export const INSIGHTS: Insight[] = [
    {id: 1, date: moment(), read: false, image: '../../assets/imgs/stocks.jpg', title: 'No Follow Through on the Move to New Highs as Narrowing Participation Worries Technical Analysts', content: "The S&P 500 Index closed on Thursday at 2,390.88, down 0.35% on the week. The anticipated breakout to new intra-day highs was accomplished on Tuesday but quickly attracted profit takers. The Nasdaq Composite, led by the strong Technology Sector, finished up on the week but small and mid-cap stocks as well as transportation stocks finished lower on the week. The breakout that we are looking for may continue to be stymied by negative seasonal patterns that usually result in an early June low as a prelude to." },
    {id: 2, date: moment(), read: false, image: '../../assets/imgs/stocks.jpg', title: 'S&P 500 Index at New Highs Ahead of French Elections, Macron Victory May Propel S&P 500', content: 'blah blah blah' },
    {id: 3, date: moment(), read: false, image: '../../assets/imgs/stocks.jpg', title: 'No Follow Through on the Move to New Highs as Narrowing Participation Worries Technical Analysts', content: 'The S&P 500 Index closed on Thursday at 2399.29, up 0.63% on the week. The Emmanuel Macron victory in the French elections takes a big negative off the table for stock markets worldwide. It may be just the impetus that the stock market in the U.S. needs to breakout above 2,400 and realize our longstanding price target for the S&P 500 Index of 2,450 -2,500.' },
    {id: 4, date: moment(), read: false, image: '../../assets/imgs/stocks.jpg', title: 'Stocks Bounce near Initial Support', content: 'MSFT triggered a Money-Flow Buy signal yesterday. The stock recently broke out to new record highs, a move supported by better-than-expected earnings. The subsequent pullback to the 21-day MA was constructive, as Money-Flow and Relative Strength remained very strong and the PGR held Bullish. The positive Chaikin Credentials suggest that MSFT’s current pause is setting the stage for a resumption of the intermediate-term uptrend. Look to buy MSFT on low-volume pullbacks in anticipation of a move towards the 73-74 area.' },
    {id: 5, date: moment(), read: false, image: '../../assets/imgs/stocks.jpg', title: 'DJIA 21,000 and SPX 2400 Remain a Challenge', content: 'STX triggered a Money-Flow Sell signal yesterday. The stock plunged on disappointing revenues last month and has not been able to recover The gap lower also took price under the LTMA and turned the PGR and Relative Strength reading negative. If STX cannot hold above the recent low (41.20) on a closing basis there is risk (i.e. an air-pocket) down to 38.00. The anemic Money-Flow readings during the current stabilization, together with the major gap down, negative Relative Strength and the Bearish PGR, suggest that the air-pocket will eventually be filled. The LTMA can be used as a stop.' },
    {id: 6, date: moment(), read: false, image: '../../assets/imgs/stocks.jpg', title: 'Stocks in Holding Pattern Ahead of GDP Data', content: 'KMX triggered Overbought Sell and Relative Strength sell signals recently. However, the stock is being propped up by the strong overall market and by an oversold rebound in the Retail area (i.e. the XRT is +7% off the April low). We look for stocks that have rebounded on weak Chaikin Credentials to sell or short and KMX fits the criteria. The multi-month trend is negative, the PGR is Bearish and Relative Strength experienced a “personality change” in April by turning negative after a prolonged period in positive territory. Money-Flow has also been weak during the current rebound and the stock has reached the 38.2% retracement level. Look to sell KMX near LTMA and Upper Band resistance in anticipation of a re-test of the lows once the SPX stalls/pulls back. The vertical put trade is also favored by OptionsPlay, with a 111 rating.' },
    {id: 7, date: moment(), read: false, image: '../../assets/imgs/stocks.jpg', title: 'Market Weekly Insight', content: 'blah blah blah' },
    {id: 8, date: moment(), read: false, image: '../../assets/imgs/stocks.jpg', title: 'Market Weekly Insight', content: 'blah blah blah' },
    {id: 9, date: moment(), read: false, image: '../../assets/imgs/stocks.jpg', title: 'Market Weekly Insight', content: 'blah blah blah' },
    {id: 10, date: moment(), read: false, image: '../../assets/imgs/stocks.jpg', title: 'Market Weekly Insight', content: 'blah blah blah' },
    {id: 11, date: moment(), read: false, image: '../../assets/imgs/stocks.jpg', title: 'Market Weekly Insight', content: 'blah blah blah' },
    {id: 12, date: moment(), read: false, image: '../../assets/imgs/stocks.jpg', title: 'Market Weekly Insight', content: 'blah blah blah' },
    {id: 13, date: moment(), read: false, image: '../../assets/imgs/stocks.jpg', title: 'Market Weekly Insight', content: 'blah blah blah' },
    {id: 14, date: moment(), read: false, image: '../../assets/imgs/stocks.jpg', title: 'Market Weekly Insight', content: 'blah blah blah' },
    {id: 15, date: moment(), read: false, image: '../../assets/imgs/stocks.jpg', title: 'Market Weekly Insight', content: 'blah blah blah' },
    {id: 16, date: moment(), read: false, image: '../../assets/imgs/stocks.jpg', title: 'Market Weekly Insight', content: 'blah blah blah' },
    {id: 17, date: moment(), read: false, image: '../../assets/imgs/stocks.jpg', title: 'Market Weekly Insight', content: 'blah blah blah' },
    {id: 18, date: moment(), read: false, image: '../../assets/imgs/stocks.jpg', title: 'Market Weekly Insight', content: 'blah blah blah' },
    {id: 19, date: moment(), read: false, image: '../../assets/imgs/stocks.jpg', title: 'Market Weekly Insight', content: 'blah blah blah' },
    {id: 20, date: moment(), read: false, image: '../../assets/imgs/stocks.jpg', title: 'Market Weekly Insight', content: 'blah blah blah' }
];